// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8weIVCZx-SkTeeLGaf576ROy06yeIHw',
    appId: '1:339441182261:web:09189bd6a24d62b6adb37c',
    messagingSenderId: '339441182261',
    projectId: 'project-djef001',
    authDomain: 'project-djef001.firebaseapp.com',
    storageBucket: 'project-djef001.appspot.com',
    measurementId: 'G-8GD8XSCGLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_suPRZMyMF4gEOBQqTmUYw1wJyIx3SOI',
    appId: '1:339441182261:android:6aa1dce465977241adb37c',
    messagingSenderId: '339441182261',
    projectId: 'project-djef001',
    storageBucket: 'project-djef001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0zMpozy4imxZ9l5hDkvn3rE8n39oGxc',
    appId: '1:339441182261:ios:19310465e657bff7adb37c',
    messagingSenderId: '339441182261',
    projectId: 'project-djef001',
    storageBucket: 'project-djef001.appspot.com',
    iosClientId:
        '339441182261-1rhgkuu0r62r2ejglfjrq4g9mmcei2kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW0zMpozy4imxZ9l5hDkvn3rE8n39oGxc',
    appId: '1:339441182261:ios:19310465e657bff7adb37c',
    messagingSenderId: '339441182261',
    projectId: 'project-djef001',
    storageBucket: 'project-djef001.appspot.com',
    iosClientId:
        '339441182261-1rhgkuu0r62r2ejglfjrq4g9mmcei2kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
